### ISSUE TITLE
go dropped get

### ISSUE THREAD

**Issue by moeller0** [heistp/cctrace#4]
When following the instructions go complained about 'go get" being not supported any more, however go install seems to work...

123-1234567:cctrace user$ go get -u github.com/heistp/cctrace
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
hms-beagle2:cctrace smoeller$ go install github.com/heistp/cctrace@latest
go: downloading github.com/heistp/cctrace v0.0.0-20190327084752-8f1f2a966635
go: finding module for package github.com/google/gopacket/pcap
go: finding module for package github.com/google/gopacket
go: finding module for package github.com/google/gopacket/layers
go: downloading github.com/google/gopacket v1.1.19
go: found github.com/google/gopacket in github.com/google/gopacket v1.1.19
go: found github.com/google/gopacket/layers in github.com/google/gopacket v1.1.19
go: found github.com/google/gopacket/pcap in github.com/google/gopacket v1.1.19
123-1234567:cctrace user$

**Comment by heistp** [comment]
Thanks, updated. Sorry for 2.5 months to change one line. :)
